### ISSUE TITLE
Map Gen Randomization

### ISSUE THREAD

**Issue by xXxSovereign** [xXxSovereign/WorldOfPlus#1]
All dungeons are generated near top, fixes: Shuffle map after creation or instead of sequentially adding random areas, randomly add random areas

**Comment by Rickxotic** [comment]
could we possibly have different light levels the further in you go so its harder for the player fov to detect enemies and such?

**Comment by Rickxotic** [comment]
also I have a few Ideas for the main menu design.

**Comment by xXxSovereign** [comment]
Post them on the ideas tab in the project manager, I'm taking a break from
the project for today.

**Comment by Rickxotic** [comment]
we could use someting like the chunk generation from minecraft to generate them more randomly and frequently, btw minecraft chunks are 16 blocks by 16 blocks by 16 blocks for x,y,z

**Comment by Rickxotic** [comment]
wait i mean Chunks are 16 blocks wide, 16 blocks long, and 256 blocks high – totaling 65,536 blocks, including air. Chunks are generated around players upon entering the world, and new chunks are generated as they wander around the world.

**Comment by xXxSovereign** [comment]
We aren't doing a 3D game this time, we are doing a 2D text based open world rpg. I'm working on generation of world maps which the player will be on

**Comment by xXxSovereign** [comment]
Random World Generation Fully Functional, variety will be increased as more area's are added
